/*!CK:2458967895!*//*1392692803,178191663*/

if (self.CavalryLogger) { CavalryLogger.start_js(["V7AXU"]); }

__d("LitestandEllipsis",["DOM","DOMDimensions","concatMap","createArrayFrom"],function(a,b,c,d,e,f,g,h,i,j){var k,l={add:function(o,p,q){q=q||o;g.scry(o,'br').forEach(g.remove);var r=h.getElementDimensions(q).height;if(r<=p)return o;var s,t='...',u=n(o),v=u.length-1,w=g.getText(u[v]);while(v>=0&&r>p){s=Math.max(w.lastIndexOf(' '),w.lastIndexOf('\n'));if(s===-1)s=w.length-t.length-1;if(s<=0){m(u[v],'');v--;w=g.getText(u[v]);}else{w=w.substr(0,s).trim()+t;m(u[v],w);}r=h.getElementDimensions(q).height;}}};function m(o,p){k=k||(o.textContent!=null?'textContent':'innerText');o[k]=p;}function n(o){if(g.isTextNode(o))return [o];return i(n,j(o.childNodes));}e.exports=l;});
__d("ShareAttachmentDescriptionEllipsis",["DOMDimensions","LitestandEllipsis","Style"],function(a,b,c,d,e,f,g,h,i){var j={add:function(k,l){var m=g.getElementDimensions(l).height,n=i.getFloat(k,'marginTop'),o=k.parentElement.clientHeight-m-n;h.add(k,o);}};e.exports=j;});
__d("PubContentTrendingUnitTruncation",["DOM","LitestandEllipsis","Style","csx"],function(a,b,c,d,e,f,g,h,i,j){var k,l={truncate:function(m){var n=g.scry(m,"._5v9v")[0];if(n){if(typeof k==='undefined'){var o=g.find(m,"._5v0u");k=i.getFloat(o,'maxHeight');}var p=g.find(m,"._5r--");h.add(n,k,p);}}};e.exports=l;});
__d("PubcontentTrendingUnitToggle",["CSS","DOM","Event","PubContentTrendingUnitTruncation","Run","csx"],function(a,b,c,d,e,f,g,h,i,j,k,l){var m={listenForToggle:function(n,o){var p=i.listen(n,'click',function(){p.remove();p=null;g.hide(n);h.scry(o,"._5my1").forEach(function(q){g.show(q);j.truncate(q);});});k.onLeave(function(){p&&p.remove();});}};e.exports=m;});
__d("TrendingRHCLogger",["AsyncSignal","CSS","Event","Parent","Run","ScubaSample","TrendingRHCConfig","cx"],function(a,b,c,d,e,f,g,h,i,j,k,l,m,n){var o,p,q,r;function s(event){var v=event.getTarget();if(!h.hasClass(v,"_5my2"))v=j.byClass(v,"_5my2");if(!v)return;var w=v.getAttribute('data-position');if(!w)return;var x=new l('trending_rhc',null,{sampleRate:m.sample_rate});x.addNormal('has_litestand',o);x.addNormal('event','click');x.addNormal('position',w);x.addNormal('qe_group',q);x.addNormal('source',r);x.flush();if(w==='seemore')t();}function t(){if(!p)return;new g('/ajax/pubcontent/trending_rhc/log_hidden',{keys:JSON.stringify(p),source:r}).send();p=null;}var u={init:function(v,w,x,y,z){r=w;o=x;q=y;p=z;var aa=i.listen(v,'click',s);k.onLeave(function(){aa.remove();});}};e.exports=u;});
__d("FbFeedAttachmentRelatedShare",["Arbiter","AttachmentRelatedShareConstants","DOM","Event","tidyEvent"],function(a,b,c,d,e,f,g,h,i,j,k){var l={loadRelatedAttachment:function(m,n){k(j.listen(m,'click',function(){g.inform(h.ARTICLE_CLICK,{attachment:m,attachment_div_id:i.getID(m),global_share_id:n});}));},loadRelatedVideoAttachment:function(m,n){k(j.listen(m,'click',function(){g.inform(h.VIDEO_CLICK,{attachment:m,attachment_div_id:i.getID(m),global_share_id:n});}));},closeButton:function(m,n){k(j.listen(m,'click',function(){i.remove(n);}));}};e.exports=l;});